[terminal.shell]
program="/usr/bin/tmux" # <- set this to the path of your tmux installation
args= ["new-session", "-A", "-D", "-s", "main"]

[font]
size = 19

[font.normal]
family = "IBM Plex Mono"
style = "Medium"

[mouse]
hide_when_typing = true

[general]
import = [ "~/.config/alacritty/themes/kanagawa_wave.toml" ]
