tap "valkyrie00/bbrew"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Yet another cross-platform graphical process/system monitor
brew "bottom"
# Linux utility to get information on filesystems, like df but better
brew "dysk"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Music Player Daemon
brew "mpd"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Terminal based Media Player Client with album art support
brew "rmpc"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# A simple TUI tool to make your homebrew bold.
brew "valkyrie00/bbrew/bbrew"
flatpak "com.github.PintaProject.Pinta"
flatpak "com.github.tchx84.Flatseal"
flatpak "com.mattjakeman.ExtensionManager"
flatpak "com.microsoft.Edge"
flatpak "com.ranfdev.DistroShelf"
flatpak "com.valvesoftware.Steam"
flatpak "dev.vencord.Vesktop"
flatpak "io.github.celluloid_player.Celluloid"
flatpak "io.github.flattool.Ignition"
flatpak "io.github.flattool.Warehouse"
flatpak "io.github.kolunmi.Bazaar"
flatpak "io.gitlab.adhami3310.Impression"
flatpak "io.missioncenter.MissionCenter"
flatpak "it.mijorus.gearlever"
flatpak "net.mullvad.MullvadBrowser"
flatpak "org.chromium.Chromium"
flatpak "org.gnome.Calculator"
flatpak "org.gnome.Calendar"
flatpak "org.gnome.Characters"
flatpak "org.gnome.Connections"
flatpak "org.gnome.Contacts"
flatpak "org.gnome.DejaDup"
flatpak "org.gnome.FileRoller"
flatpak "org.gnome.Firmware"
flatpak "org.gnome.Logs"
flatpak "org.gnome.Loupe"
flatpak "org.gnome.Maps"
flatpak "org.gnome.NautilusPreviewer"
flatpak "org.gnome.Papers"
flatpak "org.gnome.Showtime"
flatpak "org.gnome.SimpleScan"
flatpak "org.gnome.Snapshot"
flatpak "org.gnome.TextEditor"
flatpak "org.gnome.Weather"
flatpak "org.gnome.baobab"
flatpak "org.gnome.clocks"
flatpak "org.gnome.font-viewer"
flatpak "org.localsend.localsend_app"
flatpak "org.mozilla.Thunderbird"
flatpak "org.mozilla.firefox"
flatpak "org.remmina.Remmina"
flatpak "page.tesk.Refine"
