wallpaper {
    monitor = 
    path = /home/aszegedi/Pictures/wallpapers/3840x2160-dark-archlinux2.png
    fit_mode = contain
}

#enable splash text rendering over the wallpaper
splash = false 

#fully disable ipc
# ipc = off
