preload = /home/aszegedi/Pictures/wallpapers/launchpad_by_wanbao.png

wallpaper {
    monitor = 
    path = /home/aszegedi/Pictures/wallpapers/launchpad_by_wanbao.png
    fit_mode = contain
}

#enable splash text rendering over the wallpaper
splash = false 

#fully disable ipc
# ipc = off
