
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 3 
    gaps_out = 5
    border_size = 3
    col.active_border = rgba(83A598ff)
    col.inactive_border = rgba(1D2021ff)
    cursor_inactive_timeout = 10
    layout = dwindle
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 6 
    multisample_edges = yes
    blur = no 
    blur_size = 3
    blur_passes = 1
    blur_new_optimizations = on

    drop_shadow = no 
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes 
}

